
language: cpp
os: linux
compiler: gcc
sudo: required


install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qttools5-dev-tools

script:
  - qmake -project
  - qmake GUI/GUI/GUI.pro
  - make


